package frame;

import configDB.tbl_pengeluaran;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class frame_pengeluaran extends javax.swing.JFrame {

    /**
     * Creates new form frame_pengeluaran
     */
    public frame_pengeluaran() {
        initComponents();
        tampilData(); 
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable1.getSelectedRow();
        txtid.setText(jTable1.getValueAt(row, 0).toString());
        txttanggal_pengeluaran.setText(jTable1.getValueAt(row, 1).toString());
        txtnama_pengeluaran.setText(jTable1.getValueAt(row, 2).toString());
        txtnominal.setText(jTable1.getValueAt(row, 3).toString());
        txtketerangan.setText(jTable1.getValueAt(row, 4).toString());
    }
});
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txttanggal_pengeluaran = new javax.swing.JTextField();
        txtnama_pengeluaran = new javax.swing.JTextField();
        txtnominal = new javax.swing.JTextField();
        txtketerangan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnLaporan = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tgl_Pengeluaran");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nama_Pengeluaran");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nominal");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Keterangan");

        jButton1.setText("TAMBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txttanggal_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggal_pengeluaranActionPerformed(evt);
            }
        });

        txtnama_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama_pengeluaranActionPerformed(evt);
            }
        });

        txtnominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnominalActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Tabel Pengeluaran");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tgl Pengeluaran", "Nama Pengeluaran", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnLaporan.setText("Cetak Laporan");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(70, 70, 70)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtketerangan, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(txtnominal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(txtnama_pengeluaran)
                                            .addComponent(txttanggal_pengeluaran)
                                            .addComponent(txtid)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(37, 37, 37)
                                        .addComponent(jButton2)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton3)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLaporan)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttanggal_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btnLaporan)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txttanggal_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggal_pengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggal_pengeluaranActionPerformed

    private void txtnama_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama_pengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnama_pengeluaranActionPerformed

    private void txtnominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnominalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
        String url = "jdbc:mysql://localhost:3306/pbo2_2310010388";
        String user = "root";
        String pass = "";
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, pass);

        if (txtid.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan ID yang ingin dihapus!");
            return;
        }

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
                "Apakah kamu yakin ingin menghapus data ini?",
                "Konfirmasi Hapus",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM tbl_pengeluaran WHERE id=?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(txtid.getText()));

            int hasil = pst.executeUpdate();

            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "ID tidak ditemukan!");
            }

            txtid.setText("");
            txttanggal_pengeluaran.setText("");
            txtnama_pengeluaran.setText("");
            txtnominal.setText("");
            txtketerangan.setText("");
        }

        conn.close();
        tampilData();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
        // Koneksi ke database
        String url = "jdbc:mysql://localhost:3306/pbo2_2310010388";
        String user = "root";
        String pass = "";
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, pass);

        // Query untuk insert data
        String sql = "INSERT INTO tbl_pengeluaran (id, tanggal_pengeluaran, nama_pengeluaran, nominal, keterangan) VALUES (?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, Integer.parseInt(txtid.getText()));
        pst.setString(2, txttanggal_pengeluaran.getText());
        pst.setString(3, txtnama_pengeluaran.getText());
        pst.setString(4, txtnominal.getText());
        pst.setString(5, txtketerangan.getText());

        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Data pengeluaran berhasil disimpan!");

        // Kosongkan field setelah simpan
        txtid.setText("");
        txttanggal_pengeluaran.setText("");
        txtnama_pengeluaran.setText("");
        txtnominal.setText("");
        txtketerangan.setText("");

        conn.close();
        tampilData();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try {
        String url = "jdbc:mysql://localhost:3306/pbo2_2310010388";
        String user = "root";
        String pass = "";
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, pass);

        String sql = "UPDATE tbl_pengeluaran SET tanggal_pengeluaran=?, nama_pengeluaran=?, nominal=?, keterangan=? WHERE id=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txttanggal_pengeluaran.getText());
        pst.setString(2, txtnama_pengeluaran.getText());
        pst.setString(3, txtnominal.getText());
        pst.setString(4, txtketerangan.getText());
        pst.setInt(5, Integer.parseInt(txtid.getText()));

        int hasil = pst.executeUpdate();

        if (hasil > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data pengeluaran berhasil diubah!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ID tidak ditemukan!");
        }

        conn.close();
        tampilData();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + e.getMessage());
    } 
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        tampilCariPengeluaran();
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
          try {
        tbl_pengeluaran laporan = new tbl_pengeluaran();

        String file = "src/laporan/laporanPengeluaran.jrxml";

        String sql;
        if (txtCari.getText().equals("")) {
            sql = "SELECT * FROM tbl_pengeluaran";
        } else {
            sql = "SELECT * FROM tbl_pengeluaran WHERE "
                + "id LIKE '%" + txtCari.getText() + "%' OR "
                + "tanggal_pengeluaran LIKE '%" + txtCari.getText() + "%' OR "
                + "nama_pengeluaran LIKE '%" + txtCari.getText() + "%' OR "
                + "nominal LIKE '%" + txtCari.getText() + "%' OR "
                + "keterangan LIKE '%" + txtCari.getText() + "%'";
        }

        laporan.cetakLaporan(file, sql);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Gagal mencetak laporan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_pengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txtnama_pengeluaran;
    private javax.swing.JTextField txtnominal;
    private javax.swing.JTextField txttanggal_pengeluaran;
    // End of variables declaration//GEN-END:variables
private void tampilData() {
    try {
        String url = "jdbc:mysql://localhost:3306/pbo2_2310010388";
        String user = "root";
        String pass = "";
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, pass);

        String sql = "SELECT * FROM tbl_pengeluaran";
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Tgl Pengeluaran");
        model.addColumn("Nama Pengeluaran");
        model.addColumn("Nominal");
        model.addColumn("Keterangan");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("tanggal_pengeluaran"),
                rs.getString("nama_pengeluaran"),
                rs.getString("nominal"),
                rs.getString("keterangan")
            });
        }

        jTable1.setModel(model);
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
} 

private void tampilCariPengeluaran() {
    try {
        tbl_pengeluaran model = new tbl_pengeluaran();
        java.sql.ResultSet rs = model.cariPengeluaran(txtCari.getText());

        javax.swing.table.DefaultTableModel modelTable =
                new javax.swing.table.DefaultTableModel();

        modelTable.addColumn("ID");
        modelTable.addColumn("Tgl Pengeluaran");
        modelTable.addColumn("Nama Pengeluaran");
        modelTable.addColumn("Nominal");
        modelTable.addColumn("Keterangan");

        while (rs.next()) {
            modelTable.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("tanggal_pengeluaran"),
                rs.getString("nama_pengeluaran"),
                rs.getString("nominal"),
                rs.getString("keterangan")
            });
        }

        jTable1.setModel(modelTable);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal mencari data pengeluaran: " + e.getMessage());
    }
}
}
