package frame;

import configDB.tbl_pemasukan;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class frame_pemasukan extends javax.swing.JFrame {

    /**
     * Creates new form frame_pemasukan
     */
    public frame_pemasukan() {
        initComponents();
        tampilData(); 
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable1.getSelectedRow();
        txtid.setText(jTable1.getValueAt(row, 0).toString());
        txttanggal_pemasukan.setText(jTable1.getValueAt(row, 1).toString());
        txtnominal.setText(jTable1.getValueAt(row, 2).toString());
        txtasal_pemasukan.setText(jTable1.getValueAt(row, 3).toString());
        txtketerangan.setText(jTable1.getValueAt(row, 4).toString());
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttanggal_pemasukan = new javax.swing.JTextField();
        txtnominal = new javax.swing.JTextField();
        txtasal_pemasukan = new javax.swing.JTextField();
        txtketerangan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnLaporan = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tgl_Pemasukan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nominal");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Asal Pemasukan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Keterangan");

        txttanggal_pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggal_pemasukanActionPerformed(evt);
            }
        });

        txtnominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnominalActionPerformed(evt);
            }
        });

        txtasal_pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtasal_pemasukanActionPerformed(evt);
            }
        });

        txtketerangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtketeranganActionPerformed(evt);
            }
        });

        jButton1.setText("TAMBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Tabel Pemasukan");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tgl Pemasukan", "Nominal", "Asal Pemasukan", "Keterangan"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        btnLaporan.setText("Cetak Lapooran");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtid)
                            .addComponent(txttanggal_pemasukan)
                            .addComponent(txtnominal)
                            .addComponent(txtasal_pemasukan)
                            .addComponent(txtketerangan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaporan))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttanggal_pemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnLaporan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtasal_pemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnominalActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txttanggal_pemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggal_pemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggal_pemasukanActionPerformed

    private void txtketeranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtketeranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtketeranganActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
        // Koneksi ke database
        String url = "jdbc:mysql://localhost:3306/pbo2_2310010388";
        String user = "root";
        String pass = "";
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, pass);

        // Query untuk insert data
        String sql = "INSERT INTO tbl_pemasukan (id, tanggal_pemasukan, nominal, asal_pemasukan, keterangan) VALUES (?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        // Ambil data dari textfield
        pst.setInt(1, Integer.parseInt(txtid.getText()));   // id
        pst.setString(2, txttanggal_pemasukan.getText());                  // tanggal_pemasukan
        pst.setString(3, txtnominal.getText());                  // nominal
        pst.setString(4, txtasal_pemasukan.getText());                  // asal_pemasukan
        pst.setString(5, txtketerangan.getText());                  // keterangan

        // Jalankan perintah
        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");

        // Kosongkan field setelah simpan
        txtid.setText("");
        txttanggal_pemasukan.setText("");
        txtnominal.setText("");
        txtasal_pemasukan.setText("");
        txtketerangan.setText("");

        conn.close();
        tampilData();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
        // Koneksi ke database
        String url = "jdbc:mysql://localhost:3306/pbo2_2310010388";
        String user = "root";
        String pass = "";
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, pass);

        // Query UPDATE data berdasarkan ID
        String sql = "UPDATE tbl_pemasukan SET tanggal_pemasukan=?, nominal=?, asal_pemasukan=?, keterangan=? WHERE id=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        // Ambil data dari textfield
        pst.setString(1, txttanggal_pemasukan.getText());                  // tanggal_pemasukan
        pst.setString(2, txtnominal.getText());                  // nominal
        pst.setString(3, txtasal_pemasukan.getText());                  // asal_pemasukan
        pst.setString(4, txtketerangan.getText());                  // keterangan
        pst.setInt(5, Integer.parseInt(txtid.getText()));   // id

        // Jalankan update
        int hasil = pst.executeUpdate();

        if (hasil > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ID tidak ditemukan!");
        }

        // Tutup koneksi
        conn.close();
        tampilData();

        // Kosongkan field setelah ubah
        txtid.setText("");
        txttanggal_pemasukan.setText("");
        txtnominal.setText("");
        txtasal_pemasukan.setText("");
        txtketerangan.setText("");

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 try {
        // Koneksi ke database
        String url = "jdbc:mysql://localhost:3306/pbo2_2310010388";
        String user = "root";
        String pass = "";
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, pass);

        // Pastikan field ID tidak kosong
        if (txtid.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan ID yang ingin dihapus!");
            return;
        }

        // Konfirmasi sebelum hapus
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Apakah kamu yakin ingin menghapus data ini?", 
            "Konfirmasi Hapus", 
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            // Query hapus berdasarkan ID
            String sql = "DELETE FROM tbl_pemasukan WHERE id=?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(txtid.getText()));

            int hasil = pst.executeUpdate();

            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "ID tidak ditemukan!");
            }

            // Kosongkan field
            txtid.setText("");
            txttanggal_pemasukan.setText("");
            txtnominal.setText("");
            txtasal_pemasukan.setText("");
            txtketerangan.setText("");
        }

        // Tutup koneksi
        conn.close();
        tampilData();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtasal_pemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtasal_pemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtasal_pemasukanActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        tampilCariData();
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
         try {
        tbl_pemasukan lap = new tbl_pemasukan();

        // path jrxml (sesuaikan dengan folder project kamu)
        String file = "src/laporan/laporanPemasukan.jrxml";

        // cetak semua data
        String sql = "SELECT * FROM tbl_pemasukan";

        lap.cetakLaporan(file, sql);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Gagal mencetak laporan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_pemasukan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaporan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtasal_pemasukan;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txtnominal;
    private javax.swing.JTextField txttanggal_pemasukan;
    // End of variables declaration//GEN-END:variables
private void tampilData() {
    try {
        String url = "jdbc:mysql://localhost:3306/pbo2_2310010388";
        String user = "root";
        String pass = "";
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, user, pass);

        String sql = "SELECT * FROM tbl_pemasukan";
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Tgl Pemasukan");
        model.addColumn("Nominal");
        model.addColumn("Asal Pemasukan");
        model.addColumn("Keterangan");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("tanggal_pemasukan"),
                rs.getString("nominal"),
                rs.getString("asal_pemasukan"),
                rs.getString("keterangan")
            });
        }

        jTable4.setModel(model);
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
    }
}

private void tampilCariData() {
    try {
        tbl_pemasukan model = new tbl_pemasukan();
        java.sql.ResultSet rs = model.cariPemasukan(txtCari.getText());

        javax.swing.table.DefaultTableModel modelTable = 
            new javax.swing.table.DefaultTableModel();

        modelTable.addColumn("ID");
        modelTable.addColumn("Tgl Pemasukan");
        modelTable.addColumn("Nominal");
        modelTable.addColumn("Asal Pemasukan");
        modelTable.addColumn("Keterangan");

        while (rs.next()) {
            modelTable.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("tanggal_pemasukan"),
                rs.getString("nominal"),
                rs.getString("asal_pemasukan"),
                rs.getString("keterangan")
            });
        }

        jTable4.setModel(modelTable);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Gagal mencari data: " + e.getMessage());
    }
}

}
